version: "3"

services:
  mysqldb:

    image: mysql
    container_name: mysqlcicd
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: examv2thouraya
    ports:
      - "3306:3306"

  app:
    depends_on:
      - mysqldb
    image: oussamahasni/examthouraya
    container_name: houssemspring
    restart: on-failure
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqlcicd:3306/examv2thouraya?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
